# Generated by Django 4.0.4 on 2022-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instruction', models.CharField(blank=True, default='', max_length=200)),
                ('treated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('command_instruction', models.CharField(blank=True, default='', max_length=200)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
